### ISSUE TITLE
CH552T problems

### ISSUE THREAD

**Issue by molester** [kingyoPiyo/Tang-Nano_I2C_Monitor#1]
My tang nano will not load new firmware on CH552T using the procedure described. Can the CH552T be bricked somehow (yet still run the original firmware)?
My WCHSPTool output is:
** User file name:E\DOWNLOADS\USB_JTAG.BIN
** Download bytes:6222 B
User file HASH:
Via usb download CH552 firmware
Device No. is started to download
Jump to BOOT from the user area,configuration bits cannot be modified!
BTVER:02.40
UID:B9-BD-F3-60-0-0-0
Unable to revamp CfgBit when entrance BOOT without power on.
1#device device download is failure

**Comment by kingyoPiyo** [comment]
Hello, 
Connect the USB cable to the CH552T with pins 14 and 20 shorted, and then immediately remove the short. Does this still fail?
I have had success with this method. Sorry, detailed support is difficult to provide...

**Comment by molester** [comment]
Thank you very much! This method worked. All the time I used the FT_Prog method to put it in bootloader mode, but that never worked.
