### ISSUE TITLE
Is there a way to restore the CH552T firmware to the original?

### ISSUE THREAD

**Issue by charkster** [kingyoPiyo/Tang-Nano_I2C_Monitor#2]
I could not dump the original CH552T firmware which mimics the FTDI F2232H. I am worried about changing the firmware and not being able to reconfigure the tang nano FPGA in the future. Do you have the original firmware, or is there a method to program the tang nano FPGA with the new serial port firmware?
Thank you for any assistance.

**Comment by charkster** [comment]
I was able to build the new firmware with both serial port and ft2232 emulation.
https://github.com/diodep/ch55x_jtag

**Comment by charkster** [comment]
I needed to connect a 22k Ohm resistor from the Tang Nano's 3.3V pin to the USB D+ line when using the WCHISPTool. No need to use the FTDI software as the CH552 is already in DFU mode.

**Comment by kingyoPiyo** [comment]
Sorry for the late reply. I am glad to hear that you have resolved the issue.
